[package]
name = "hello-word"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7"
async-graphql-axum = "7"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
sea-orm = { version = "1", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
dotenvy = "0.15"
