[package]
name = "be-toko-online-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4.0"
async-graphql-axum = "4.0"
axum = "0.5"
dotenvy = "0.15"
sea-orm = { version = "0.11", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tower = "0.4"
hyper = { version = "0.14", features = ["full"] }